apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: leoguerarti/gitopsfc
  newTag: 3ae245bdb835b5b1c3713b5ba6ddc81118b9c058
